### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by ratsey** [apioo/fusio-tools-vscode#1]
I have the extension installed, have connected to my Fusio instance and see the set of Actions and Schemas listed.

App_Action_Todo_Delete
App_Action_Todo_Row
etc.

What is shown in the Action, when I click it, seems to be JSON describing the action but it's in a comment block and it's not obvious to me what I can do with it. I tried saving it, removing the comments, etc. Saving it seems to do something as I see the Actions block in VSCode trigger a moving line, as if indicating something is happening. But the back end is unchanged and if I click on the Action again, it reverts to whatever was originally there.

I also see a notice that says 'Provided action class is not supported'

The extension instructions indicate that I should be able to load, create, run actions. Is that correct?

Ideally I would love to be able to do everything from within VSCode remotely and not have to edit files on my host Linux server. Is there any additional help available?

**Comment by chriskapp** [comment]
Sure, so currently the extension only enables you to edit "PHP-Sandbox" and "Worker-*" Actions since there we store the code at the database. So the VSCode extension can set all settings via the API. Since we have no file access we cant upload actual files to the remote Fusio instance. For actions which are not supported we simply output the settings of the action as comment and this is basically what you see. Which kind of actions do you currently use, in the future we may add also support for other actions.

**Comment by ratsey** [comment]
I have a few PHP class file actions that do things like trigger emails and such, but the majority are (will be!) plain SQL selects and updates to MySQL. Could those be database homed?
